// import Head from 'next/head'
// import Image from 'next/image'
// import Link from 'next/link'
// import { useSession, signIn, signOut } from 'next-auth/react'
// // import { data } from 'autoprefixer'




// export default function Header(){
//     // const [session] = useSession();

//     const {data:session} = useSession()

   

//     console.log("session",session)
    
    
//     return(
//       <>
//         <Head>
//         <title>Field Simplified</title>
//         <meta name="description" content="Generated by create next app" />
//         {/* <link rel="icon" href="/favicon.ico" /> */}
//       </Head>
//       <header className="text-gray-700 body-font border-b border-gray-200">
//          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
//             <Link className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" href="/" target="_blank">
//             <Image src="/fieldlogo.png" alt="" width={100} height={50}></Image>
//             </Link>
//         <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
//         {/* <Link href ="/login"> */}
//           {/* <button  className="mr-5 hover:text-gray-900">
//           You are signed in as {session}
//           </button> */}
//           {/* </Link> */}
//           {/* <Link href="/register"> */}
//           {/* <button  className="mr-5 hover:text-gray-900">
//             You are not signed in{!session}
//           </button> */}
//           {/* </Link> */}
//           {/* if(session){session.user.email} */}
//           {session?<button onClick={()=>signOut()}>Log out</button>:<button onClick={()=>{
//             router.push("/api/auth/signin")
//           }}>Sign In </button>}
//         </nav>
//         </div>
//       </header>
// </>

    
//     )
// }

import { useSession, signIn, signOut } from "next-auth/react"

export default function Header() {
  const { data: session } = useSession()
  
  if (session) {
    return (
      <>
        Signed in as {session.user.name} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )
}